# # GitLab CI Job Configuration
#
# Goal: Run all jobs defined here on all available runners (GNU/Linux and
# Windows).
# 
# Procedure: Use GitLab job templates in ".gitlab/ci/templates/" and use them
# in the job description by using the "extend" keyword.
#
# ## Job Description Syntax
#
# <job_name>:                   # Job name which is displayed in web interface.
#   stage: <stage_name>         # Run "script" commands in this stage. The
#                               # stages are exececuted sequentially.
#   script:
#      - <arbitrary_commands>   # Here you can execute arbitratry terminal
#                               # commands. If any of the commands return a
#                               # non-zero exit code, the job fails.
#
# ## References
#
# - https://docs.gitlab.com/ee/ci/yaml/README.html

# Variable Definitions
variables:
    VADERE_DEPLOYMENT_BASE_URL: "http://www.vadere.org/builds"
    VADERE_PACKAGE_NAME: "vadere.${CI_COMMIT_REF_NAME}.${CI_ENVIRONMENT_NAME}.zip"

# Stage Definitions
stages:
    - unit_test
    - integration_test
    - deploy

# PLEASE, OMIT FOLLOWING GITLAB PITFALLS:
#
# 1. "include: .gitlab/ci/windows_jobs.yml" does not work!
#    Seems a bug in GitLab's "include" statement. Therefore, define all jobs
#    directly here.
# 2. Variables from "variables" section are not expanded correctly in "url"
#    section of an "environment".
.template_unit_tests:
    stage: unit_test
    
    # Skip OpenCL tests by using "-Dtest=!Test1,!Test2,..." because GitLab
    # runners do not support OpenCL.
    script:
        - mvn clean
        - mvn -Dtest=!TestConvolution,!TestBitonicSort,!TestCLLinkedList,!TestCLOptimalStepsModel test
        - python3 Tools/ContinuousIntegration/collect_line_and_branch_coverage.py
        
    artifacts:
        when: on_success
        paths:
            - "*/target/site/coverage-reports"
        expire_in: 1 week
            
.template_scenario_files:
    stage: integration_test

    script:
        - mvn clean
        - mvn -Dmaven.test.skip=true package
        - python3 Tools/ContinuousIntegration/run_vadere_console_with_all_scenario_files.py
        
    artifacts:
        when: on_failure
        paths:
            - "log_dir"
        expire_in: 1 week

.template_seed_test:
    stage: integration_test

    script:
        - mvn clean
        - mvn -Dmaven.test.skip=true package
        - python3 Tools/VadereAnalysisTools/VadereAnalysisTool/setup.py install --user
        - python3 Tools/ContinuousIntegration/run_seed_comparison_test.py
        
    artifacts:
        when: on_failure
        paths: 
            - "Tools/ContinuousIntegration/run_seed_comparison_test.d/output"
        expire_in: 1 week

.template_deploy_branch:
    stage: deploy
    
    script:
        - mvn clean
        - mvn -Dmaven.test.skip=true package
        - python3 -m zipfile -c ${VADERE_PACKAGE_NAME} VadereModelTests/ VadereGui/target/vadere.jar VadereSimulator/target/vadere-console.jar
        - scp ${VADERE_PACKAGE_NAME} di49mur@webdev-mwn.lrz.de:~/webserver/htdocs/builds/branches/${VADERE_PACKAGE_NAME}
        
    when: manual

# Job Definitions

# PLEASE, OMIT FOLLOWING GITLAB PITFALLS:
#
# 1. "include: .gitlab/ci/windows_jobs.yml" does not work!
#    Seems a bug in GitLab's "include" statement. Therefore, define all jobs
#    directly here.
# 2. Variables from "variables" section are not expanded correctly in "url"
#    section of an "environment".

# Jobs for GNU/Linux runner (which is labelled with tag "linux")
run_unit_tests_on_linux:
    extends: .template_unit_tests
    tags:
        - linux

run_scenario_files_on_linux:
    extends: .template_scenario_files
    tags:
        - linux

run_seed_test_on_linux:
    extends: .template_seed_test
    tags:
        - linux

deploy_branch_on_linux:
    extends: .template_deploy_branch
    tags:
        - linux        
    environment:
        name: linux
        url: ${VADERE_DEPLOYMENT_BASE_URL}/branches/vadere.${CI_COMMIT_REF_NAME}.${CI_ENVIRONMENT_NAME}.zip

# Jobs for Windows runner (which is labelled with tag "windows")
run_unit_tests_on_windows:
    extends: .template_unit_tests
    tags:
        - windows

run_scenario_files_on_windows:
    extends: .template_scenario_files
    tags:
        - windows

run_seed_test_on_windows:
    extends: .template_seed_test
    tags:
        - windows

deploy_on_windows:
    extends: .template_deploy
    tags:
        - windows

deploy_branch_on_windows:
    extends: .template_deploy_branch
    tags:
        - windows        
    environment:
        name: windows
        # WATCH OUT: Variables from "variables" section are not expanded correctly here.
        url: ${VADERE_DEPLOYMENT_BASE_URL}/branches/vadere.${CI_COMMIT_REF_NAME}.${CI_ENVIRONMENT_NAME}.zip
