# # GitLab CI Job Configuration
#
# Goal: Run all jobs defined here on all available runners (GNU/Linux and
# Windows).
# 
# Procedure: Use GitLab job templates in ".gitlab/ci/templates/" and use them
# in the job description by using the "extend" keyword.
#
# ## Job Description Syntax
#
# <job_name>:                   # Job name which is displayed in web interface.
#   stage: <stage_name>         # Run "script" commands in this stage. The
#                               # stages are exececuted sequentially.
#   script:
#      - <arbitrary_commands>   # Here you can execute arbitratry terminal
#                               # commands. If any of the commands return a
#                               # non-zero exit code, the job fails.
#
# ## References
#
# - https://docs.gitlab.com/ee/ci/yaml/README.html

# Variable Definitions
variables:
    VADERE_DEPLOYMENT_BASE_URL: "http://www.vadere.org/builds"
    VADERE_PACKAGE_NAME: "vadere.${CI_COMMIT_REF_NAME}.${CI_ENVIRONMENT_NAME}.zip"

# Stage Definitions
stages:
    - deploy

include: .gitlab/ci/templates/deploy_stage_templates.yml
# include: .gitlab/ci/templates/test_stage_templates.yml

# Job Definitions

# PLEASE, OMIT FOLLOWING GITLAB PITFALLS:
#
# 1. "include: .gitlab/ci/windows_jobs.yml" does not work!
#    Seems a bug in GitLab's "include" statement. Therefore, define all jobs
#    directly here.
# 2. Variables from "variables" section are not expanded correctly in "url"
#    section of an "environment".

# Jobs for GNU/Linux runner (which is labelled with tag "linux")
deploy_branch_on_linux:
    extends: .template_deploy_branch
    tags:
        - linux        
    environment:
        name: linux
        url: ${VADERE_DEPLOYMENT_BASE_URL}/branches/vadere.${CI_COMMIT_REF_NAME}.${CI_ENVIRONMENT_NAME}.zip

# Jobs for Windows runner (which is labelled with tag "windows")
deploy_branch_on_windows:
    extends: .template_deploy_branch
    tags:
        - windows        
    environment:
        name: windows
        # WATCH OUT: Variables from "variables" section are not expanded correctly here.
        url: ${VADERE_DEPLOYMENT_BASE_URL}/branches/vadere.${CI_COMMIT_REF_NAME}.${CI_ENVIRONMENT_NAME}.zip
