unit_tests_with_coverage:
  # A job is always executed within a stage.
  # If no stage is set, it defaults to 'test'.
  stage: test
  
  # Here you can execute arbitrate terminal commands.
  # If any of the commands returns a non zero exit code the job fails.
  # 
  # Watch out: OpenCL code cannot be run on virtual machine. Therefore,
  # skip this tests.
  #
  # The comma-separated list of tests after "-Dtest=<list>" is skipped.
  # All other tests are executed normally.
  #
  # Watch out: on some CI instances the exclamation mark must be escaped by a
  # backslash. Otherwise, it is interpreted by the executing shell as special
  # command.
  #
  # Following syntaxes allow you to skip whole classes and single methods:
  #
  #   #Exclude one test class
  #   mvn -Dtest=!LegacyTest test
  #   # Exclude one test method
  #   mvn -Dtest=!LegacyTest#testFoo verify 
  #   # Exclude two test methods
  #   mvn -Dtest=!LegacyTest#testFoo+testBar verify 
  #   # Exclude a package with a wildcard (*)
  #   mvn -Dtest=!com.mycompany.app.Legacy* test 
  script:
    - mvn clean
    - mvn -Dtest=!TestConvolution,!TestBitonicSort,!TestCLLinkedList test
    - python3 Tools/collect_line_and_branch_coverage.py

run_scenario_files:
  stage: deploy

  script:
      - mvn clean
      - mvn -Dmaven.test.skip=true package
      - python3 Tools/run_vadere_console_with_all_scenario_files.py

