# # GitLab CI Job Configuration
#
# Goal: Run all jobs defined here on all available runners (GNU/Linux and
# Windows).
# 
# ## Job Description Syntax
#
# <job_name>:                   # Job name which is displayed in web interface.
#   stage: <stage_name>         # Run "script" commands in this stage. The
#                               # stages are exececuted sequentially.
#   script:
#      - <arbitrary_commands>   # Here you can execute arbitratry terminal
#                               # commands. If any of the commands return a
#                               # non-zero exit code, the job fails.
#
# ## References
#
# - https://docs.gitlab.com/ee/ci/yaml/README.html

# Variable Definitions
variables:
    VADERE_DEPLOYMENT_BASE_URL: "http://www.vadere.org/builds"
    VADERE_PACKAGE_NAME: "vadere.${CI_COMMIT_REF_NAME}.${CI_COMMIT_SHA}.${CI_ENVIRONMENT_NAME}"
# Stage Definitions
stages:
    - deploy

include: .gitlab/ci/templates/deploy_stage_templates.yml
# include: .gitlab/ci/templates/test_stage_templates.yml

# Job Definitions

## Jobs for Windows runner (which is labelled with tag "windows")
deploy_branch_on_windows:
    extends: .template_deploy_branch
    tags:
        - windows
    environment:
        name: windows
        url: ${VADERE_DEPLOYMENT_BASE_URL}/branches/vadere-console.${CI_COMMIT_REF_NAME}.${CI_COMMIT_SHA}.${CI_ENVIRONMENT_NAME}.jar"
