unit_tests_with_coverage:
  # A job is always executed within a stage.
  # If no stage is set, it defaults to 'test'.
  stage: test
  
  # Here you can execute arbitrate terminal commands.
  # If any of the commands returns a non zero exit code the job fails.
  # 
  # Watch out: OpenCL code cannot be run on virtual machine. Therefore,
  # skip this tests.
  #
  # Use following (exclamation) syntax to skip test(s). Please note,
  # exclamation mark may be inserted to escape the "!".
  #
  #   #Exclude one test class, by using the explanation mark (!)
  #   mvn test -Dtest=!LegacyTest
  #   # Exclude one test method
  #   mvn verify -Dtest=!LegacyTest#testFoo
  #   # Exclude two test methods
  #   mvn verify -Dtest=!LegacyTest#testFoo+testBar
  #   # Exclude a package with a wildcard (*)
  #   mvn test -Dtest=!com.mycompany.app.Legacy*
  script:
    - mvn clean
    - mvn test -Dtest=!TestConvolution,!TestBitonicSort,!TestCLLinkedList
    
