# # GitLab CI Job Configuration
#
# Goal: Run all jobs defined here on all available runners (GNU/Linux and
# Windows).
# 
# ## Job Description Syntax
#
# <job_name>:                   # Job name which is displayed in web interface.
#   stage: <stage_name>         # Run "script" commands in this stage. The
#                               # stages are exececuted sequentially.
#   script:
#      - <arbitrary_commands>   # Here you can execute arbitratry terminal
#                               # commands. If any of the commands return a
#                               # non-zero exit code, the job fails.
#
# ## References
#
# - https://docs.gitlab.com/ee/ci/yaml/README.html

stages:
    - unit_test
    - integration_test

include: .gitlab-ci-templates.yml

# Jobs for GNU/Linux runner (which is labelled with tag "linux")
run_unit_tests_on_linux:
    extends: .template_unit_tests
    tags:
        - linux

run_scenario_files_on_linux:
    extends: .template_scenario_files
    tags:
        - linux

run_seed_test_on_linux:
    extends: .template_seed_test
    tags:
        - linux
        
# Jobs for Windows runner (which is labelled with tag "windows")
run_unit_tests_on_windows:
    extends: .template_unit_tests
    tags:
        - windows

run_scenario_files_on_windows:
    extends: .template_scenario_files
    tags:
        - windows

run_seed_test_on_windows:
    extends: .template_seed_test
    tags:
        - windows
