# # GitLab CI Job Configuration
#
# Goal: Run all jobs defined here on all available runners (GNU/Linux and
# Windows).
# 
# ## Job Description Syntax
#
# <job_name>:                   # Job name which is displayed in web interface.
#   stage: <stage_name>         # Run "script" commands in this stage. The
#                               # stages are exececuted sequentially.
#   script:
#      - <arbitrary_commands>   # Here you can execute arbitratry terminal
#                               # commands. If any of the commands return a
#                               # non-zero exit code, the job fails.
#
# ## References
#
# - https://docs.gitlab.com/ee/ci/yaml/README.html

stages:
    - unit_test
    - integration_test
    - deploy

include: .gitlab-ci-templates.yml

# Jobs for GNU/Linux runner (which is labelled with tag "linux")

deploy_on_windows:
    extends: .template_deploy
    tags:
        - linux
        
# Jobs for Windows runner (which is labelled with tag "windows")

deploy_on_windows:
    extends: .template_deploy
    tags:
        - windows
